### ISSUE TITLE
"Error handling request"

### ISSUE THREAD

**Issue by mbeavitt** [rckclmbr/pyportify#105]
first time using pyportify, got to the last page after I opened the browser and it just gave me the background image. Copied this from the cmd window, help would be much appreciated!

Listening on http://0.0.0.0:3132
Please open your browser window to http://localhost:3132
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 265, in start
  File "site-packages\aiohttp\web.py", line 96, in handle_request
  File "pyportify\middlwares.py", line 18, in index_handler
  File "pyportify\app.py", line 117, in transfer_start
  File "pyportify\app.py", line 141, in transfer_playlists
  File "pyportify\spotify.py", line 77, in fetch_playlist_tracks
  File "pyportify\spotify.py", line 71, in fetch_saved_tracks
  File "pyportify\spotify.py", line 61, in _http_get_all
  File "pyportify\spotify.py", line 122, in _http_get
Exception: Error: {'error': {'status': 403, 'message': 'Insufficient client scop
e'}}, url: https://api.spotify.com/v1/me/tracks

**Comment by rckclmbr** [comment]
You need more permissions when you get the all key, or spotify premium if
you don't have it

**Comment by rckclmbr** [comment]
*api key

**Comment by mbeavitt** [comment]
Yeah, I've got spotify premium and I checked both "playlist-read-private" and "playlist-read-collaborative" after clicking "get OAuth token". Any ideas? Thanks for replying so quickly

**Comment by rckclmbr** [comment]
Some others had this problem -- try checking all the boxes

**Comment by mbeavitt** [comment]
Alright cool, that actually helped some. It followed the process onto finding all the playlists and onto the "saved tracks" page. Unfortunately I got another error.

Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 265, in start
  File "site-packages\aiohttp\web.py", line 96, in handle_request
  File "pyportify\middlwares.py", line 18, in index_handler
  File "pyportify\app.py", line 117, in transfer_start
  File "pyportify\app.py", line 169, in transfer_playlists
  File "asyncio\futures.py", line 358, in __iter__
  File "asyncio\tasks.py", line 290, in _wakeup
  File "asyncio\futures.py", line 274, in result
  File "asyncio\tasks.py", line 239, in _step
  File "pyportify\app.py", line 236, in search_gm_track
  File "pyportify\google.py", line 59, in find_best_track
  File "pyportify\google.py", line 52, in search_all_access
  File "pyportify\google.py", line 112, in _http_get
  File "site-packages\aiohttp\client.py", line 519, in __iter__
  File "site-packages\aiohttp\client.py", line 162, in _request
  File "site-packages\aiohttp\client_reqrep.py", line 81, in __init__
  File "site-packages\yarl\__init__.py", line 674, in with_query
  File "yarl\_quoting.pyx", line 49, in yarl._quoting._quote (yarl/_quoting.c:14
44)
  File "yarl\_quoting.pyx", line 74, in yarl._quoting._do_quote (yarl/_quoting.c
:1735)
ValueError: Unallowed PCT % P

**Comment by therightstuff** [comment]
i have the same problem, i believe it occurs when the track name contains a quotation mark:

Found 'FPU - Crockett's Theme' in Google Music
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 265, in start
  File "site-packages\aiohttp\web.py", line 96, in handle_request
  File "pyportify\middlwares.py", line 18, in index_handler
  File "pyportify\app.py", line 117, in transfer_start
  File "pyportify\app.py", line 169, in transfer_playlists
  File "asyncio\futures.py", line 358, in __iter__
  File "asyncio\tasks.py", line 290, in _wakeup
  File "asyncio\futures.py", line 274, in result
  File "asyncio\tasks.py", line 239, in _step
  File "pyportify\app.py", line 236, in search_gm_track
  File "pyportify\google.py", line 59, in find_best_track
  File "pyportify\google.py", line 52, in search_all_access
  File "pyportify\google.py", line 112, in _http_get
  File "site-packages\aiohttp\client.py", line 519, in __iter__
  File "site-packages\aiohttp\client.py", line 162, in _request
  File "site-packages\aiohttp\client_reqrep.py", line 81, in __init__
  File "site-packages\yarl\__init__.py", line 674, in with_query
  File "yarl\_quoting.pyx", line 49, in yarl._quoting._quote (yarl/_quoting.c:1444)
  File "yarl\_quoting.pyx", line 74, in yarl._quoting._do_quote (yarl/_quoting.c:1735)
ValueError: Unallowed PCT % D
