### ISSUE TITLE
Can't import relatively large playlist - stops at ~20 songs

### ISSUE THREAD

**Issue by ModWilliam** [rckclmbr/pyportify#109]
Hi,

I've been able to import some smaller playlists, but I have an ~80 song playlist that I can't seem to be able to transfer. In the command line, I get this message

```
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 265, in s
  File "site-packages\aiohttp\web.py", line 96, in handl
  File "pyportify\middlwares.py", line 18, in index_hand
  File "pyportify\app.py", line 117, in transfer_start
  File "pyportify\app.py", line 169, in transfer_playlis
  File "asyncio\futures.py", line 358, in __iter__
  File "asyncio\tasks.py", line 290, in _wakeup
  File "asyncio\futures.py", line 274, in result
  File "asyncio\tasks.py", line 239, in _step
  File "pyportify\app.py", line 239, in search_gm_track
  File "pyportify\spotify.py", line 14, in search_query
TypeError: argument of type 'NoneType' is not iterable
```

and then it finds ~20 songs. From the UI, it says that I have found 20 songs and not found 0. 

I've tried this from both the windows .exe and running the code on a Mac

**Comment by rckclmbr** [comment]
pyportify has worked with 1000+ songs, there must be something going on with this playlist.  Is it public, or could you make it public and send me a link?

**Comment by ModWilliam** [comment]
Here's the playlist
https://open.spotify.com/user/22ujgyiomxbgggsb7mvnorh7q/playlist/3OVXBy5QDsx1jdSHrkAu1L

**Comment by ModWilliam** [comment]
Any update on this?

**Comment by rckclmbr** [comment]
Give 0.3.15 a try

Windows:

https://github.com/rckclmbr/pyportify/releases/download/v0.3.15/pyportify.zip

OSX:

https://github.com/rckclmbr/pyportify/releases/download/v0.3.15/pyportify.dmg

**Comment by ModWilliam** [comment]
Works, thanks!
