### ISSUE TITLE
error while installing pyportify

### ISSUE THREAD

**Issue by abby0212** [rckclmbr/pyportify#112]
i am getting this error how to slove it 
`root@abby:~/Downloads/WhatsApp-GD-Extractor-master# pip install pyportify Requirement already satisfied: pyportify in /usr/local/lib/python2.7/dist-packages/pyportify-0.3.15-py2.7.egg
Collecting aiohttp==2.1.0 (from pyportify)
  Using cached aiohttp-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    aiohttp/_http_parser.pyx: cannot find cimported module '.'
    Compiling aiohttp/_websocket.pyx because it depends on /usr/local/lib/python2.7/dist-packages/Cython/Includes/cpython/weakref.pxd.
    Compiling aiohttp/_http_parser.pyx because it depends on /usr/local/lib/python2.7/dist-packages/Cython/Includes/cpython/weakref.pxd.
    [1/2] Cythonizing aiohttp/_http_parser.pyx
    [2/2] Cythonizing aiohttp/_websocket.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iwmMMe/aiohttp/setup.py", line 64, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iwmMMe/aiohttp/
`

**Comment by rckclmbr** [comment]
You are using python 2.7. Try python 3.5

**Comment by abby0212** [comment]
i hve also install python 3.5 but don't know how to install pyportify on python3.5

**Comment by rckclmbr** [comment]
Try

  pip uninstall pyportify
  pip3 install pyportify
