### ISSUE TITLE
Valid MAC cannot be determined

### ISSUE THREAD

**Issue by Horathmael** [rckclmbr/pyportify#124]
This occurs when I try to sign in with my google account
"Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 265, in start
  File "site-packages\aiohttp\web.py", line 96, in handle_request
  File "pyportify\middlewares.py", line 18, in index_handler
  File "pyportify\app.py", line 51, in google_login
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\google.py", line 27, in login
  File "pyportify\google.py", line 207, in _get_android_id
OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs)."

**Comment by rckclmbr** [comment]
This is really weird -- pythons `uuid.getnode` can't find a valid mac address from a network interface card.  Are you running this in a VM or something?  Can you give me a little more detail on what OS/install you are running this on?  Also, did you download the executable?

**Comment by Horathmael** [comment]
I have downloaded the executable, and I am running it on Windows 10 Home, version 1703, OS Build 15063.726,

**Comment by DemanRisu** [comment]
Also getting this in 0.4.0:

Traceback (most recent call last):
  File "site-packages\aiohttp\web_protocol.py", line 416, in start
  File "site-packages\aiohttp\web.py", line 323, in _handle
  File "pyportify\middlewares.py", line 14, in index_handler
  File "pyportify\app.py", line 49, in google_login
  File "pyportify\google.py", line 25, in login
  File "pyportify\google.py", line 175, in _get_android_id
OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs).

Windows 10 Home 1709 OS build 16299.125.

**Comment by sizarkamar** [comment]
I have the same problem, I'm running 0.4.1 on Windows 10
Is there any solution for it?

**Comment by H3av3N-UK** [comment]
Really weird, this was working for me yesterday no problems at all ( had to use the standard .exe though, and complete via the web browser as copy-all would fail.

Trying it again today, and receiving the same error as the others reporting above.

Running Windows 10 Pro 64-bit
Version 1803
Build 17134.191

**Comment by minimino** [comment]
Okay so an update on this. It seems that _google.py_ is causing the issue here. Removing these lines (173-176) made it work perfectly:

`if (mac_int >> 40) % 2:
        raise OSError("a valid MAC could not be determined."
                      " Provide an android_id (and be"
                      " sure to provide the same one on future runs).")`

Maybe we should find another way to verify it is a valid MAC address.

**Comment by ColdSphinX** [comment]
same here version 0.4.1

**Comment by silicondosa** [comment]
> Okay so an update on this. It seems that _google.py_ is causing the issue here. Removing these lines (173-176) made it work perfectly:
> 
> `if (mac_int >> 40) % 2: raise OSError("a valid MAC could not be determined." " Provide an android_id (and be" " sure to provide the same one on future runs).")`
> 
> Maybe we should find another way to verify it is a valid MAC address.

I had the same issue on Linux, with pyportify installed from pip. This fix did solve the problem, but we should probably find a more permanent solution to this issue...
