### ISSUE TITLE
cannot import name 'unquote'

### ISSUE THREAD

**Issue by invious** [rckclmbr/pyportify#128]
```cannot import name 'unquote' pyportify-copyall
Traceback (most recent call last):
  File "/usr/local/bin/pyportify-copyall", line 7, in <module>
    from pyportify.copy_all import main
  File "/usr/local/lib/python3.6/site-packages/pyportify/copy_all.py", line 12, in <module>
    from pyportify import app
  File "/usr/local/lib/python3.6/site-packages/pyportify/app.py", line 11, in <module>
    from aiohttp import web, ClientSession
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 15, in <module>
    from . import (hdrs, web_exceptions, web_fileresponse, web_middlewares,
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 5, in <module>
    from aiohttp.web_urldispatcher import SystemRoute
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 20, in <module>
    from yarl import URL, unquote
ImportError: cannot import name 'unquote'
```

**Comment by Marat555** [comment]
same error

**Comment by johnsinco** [comment]
+1

**Comment by mchelem** [comment]
This is related to https://github.com/aio-libs/aiohttp/issues/2662.

The workaround is to downgrade yarl to 0.18.0.

```
pip uninstall yarl
pip install yarl==0.18.0
```

**Comment by FSund** [comment]
Seems like this bug still exists on the version uploaded to PyPi, but I think the latest version on Github is fixed. Not sure how to go about uploading the new version, so just wanted to give a notification here.

**Comment by rckclmbr** [comment]
Whoops, thanks for letting me know.  Just updated pypi too.
