### ISSUE TITLE
Cant Log in to Google

### ISSUE THREAD

**Issue by infdaze** [rckclmbr/pyportify#17]
I tried using an app-specific password and get:

127.0.0.1 - - [2015-03-06 09:31:45] "POST /google/login HTTP/1.1" 500 412 0.060079

**Comment by wilson18** [comment]
I was litterally just about to post this as an issue!

**Comment by rckclmbr** [comment]
I just tried this myself, it appears to be working fine (using two accounts).  Is there anything else special about your account?

**Comment by wilson18** [comment]
The only difference I can think of is that mine is a google apps for business account. When I try and log in, it just instantly says failed. If i then remove the two factor authentication and click sign in again, it works instantly. I will have another look later one once my music has been transferred over! (Thanks for the program btw, great work!)

**Comment by infdaze** [comment]
I don't think there is anything special. I'm going to try wiresharking when i am home and see if there is anything additional in the response or anything weird in the request. I'm on a Mac FYI

**Comment by wilson18** [comment]
Btw, I was running it within a Ubuntu VM

**Comment by brycied00d** [comment]
I too am experiencing this same 500 response back from pyportify's backend. Based on the traceback from pyportify (stderr is gobbled up by flask, but I can see it thanks to strace), and the identical traceback from pyportify-copyall, the issue looks to be rooted in gmusicapi.

```
Traceback (most recent call last):
  File "/usr/bin/pyportify-copyall", line 9, in <module>
    load_entry_point('pyportify==0.2.0', 'console_scripts', 'pyportify-copyall')()
  File "/usr/lib/python2.7/site-packages/pyportify/copy_all.py", line 17, in main
    app.user_scope.google_login(google_email, google_pass)
  File "/usr/lib/python2.7/site-packages/pyportify/views.py", line 55, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 39, in login
    if not self.session.login(email, password):
  File "/usr/lib/python2.7/site-packages/gmusicapi/session.py", line 147, in login
    success = super(Mobileclient, self).login(email, password, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gmusicapi/session.py", line 107, in login
    res = ClientLogin.perform(self, True, email, password)
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/lib/python2.7/site-packages/gmusicapi/session.py", line 75, in send
    res = self._send_without_auth(req_kwargs, new_session)
  File "/usr/lib/python2.7/site-packages/gmusicapi/session.py", line 42, in _send_without_auth
    return rsession.request(**req_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 256, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
TypeError: __init__() got an unexpected keyword argument 'server_hostname'
```

This is using the gmusicapi (4.0.0) that pip installed with pyportify (0.2.0). My account does use two-factor, but I'm feeding pyportify an application password. Host is Arch Linux (up to date). 
There's nothing useful in $HOME/.cache/gmusicapi/log/gmusicapi.log
```
!-- begin debug log --!
version: 4.0.0
logging to: $HOME/.cache/gmusicapi/log/gmusicapi.log
2015-03-06 16:26:48,393 - gmusicapi.Mobileclient1 (shared:70) [INFO]: initialized
2015-03-06 16:26:48,393 - gmusicapi.Mobileclient1 (shared:93) [INFO]: logged out
2015-03-06 16:27:03,342 - gmusicapi.Mobileclient1 (shared:204) [DEBUG]: ClientLogin(<omitted>)
```

**Comment by infdaze** [comment]
I can't see anything from the headers in Wireshark since traffic is HTTPS but calls are being made to google's servers

**Comment by infdaze** [comment]
I turned off 2FA and the issue still appears.

**Comment by rckclmbr** [comment]
@brycied00d thanks for the stack trace, that helps a lot.  I've been thinking of ditching gmusicapi completely, I'm only using a small subset of the api anyway.  I'll get this fixed.

**Comment by rckclmbr** [comment]
To clarify, this is happening on Python 2.7.8+, see shazow/urllib3#482 for more info

**Comment by rckclmbr** [comment]
This should be fixed in f9194fb99694b5398fb6a27717833d6728c59e32

**Comment by brycied00d** [comment]
Confirmed fixed. Thanks for fixing this! :)

**Comment by LaserLennart** [comment]
I have the same problem, how do update to the version with the fix?
I am using Ubuntu and I have followed the steps in the Readme to install and tried apt-get update/upgrade but nothing works.
