### ISSUE TITLE
Using Google Apps account, I cannot change security, and then authentification on Google is broken

### ISSUE THREAD

**Issue by oversanne** [rckclmbr/pyportify#29]
Hello,

I cannot connect to Google (logs below), and I cannot change my settings account because I'm using a Google Apps account.

Is there another way to anthenticate?

Thanks!!

Olivier

```
192.168.99.1 - - [2015-06-09 11:41:55] "POST /google/login HTTP/1.1" 500 412 0.080874
2015-06-09 11:42:03,502 - pyportify.views - ERROR - Exception on /google/login [POST]
Traceback (most recent call last):
  File "/ve/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/ve/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/ve/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/ve/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ve/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/ve/local/lib/python2.7/site-packages/pyportify/views.py", line 88, in google_login
    user_scope.google_login(email, password)
  File "/ve/local/lib/python2.7/site-packages/pyportify/views.py", line 60, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
  File "/ve/local/lib/python2.7/site-packages/pyportify/google.py", line 55, in login
    auth = parse_auth_response(data).get("Auth", None)
  File "/ve/local/lib/python2.7/site-packages/pyportify/google.py", line 170, in parse_auth_response
    k, v = line.split("=", 1)
ValueError: need more than 1 value to unpack
192.168.99.1 - - [2015-06-09 11:42:03] "POST /google/login HTTP/1.1" 500 412 0.072171
```

**Comment by rckclmbr** [comment]
This was actually an error we were seeing with a previous version of pyportify, are you running the latest version?

Try ```pip install --upgrade pyportify```

**Comment by jnv** [comment]
Hi, this is indeed a problem with an older version of pyportify. I am getting an identical error when using your Docker image; when I pull the repository and build the image myself, pyportify works flawlessly. Perhaps the image has to be updated?
