### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nmggithub** [rckclmbr/pyportify#34]
Here is the error:
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pyspotify
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 66: ordinal not in range(128)

What is wrong?

**Comment by rckclmbr** [comment]
This should be resolved by moving to python3
