### ISSUE TITLE
Error on Fedora 22

### ISSUE THREAD

**Issue by philtrick** [rckclmbr/pyportify#36]
Hi, I have tried pyportify following the instructions in README.md and I get the following problem when starting up:

 phil  ~  pyportify
Traceback (most recent call last):
  File "/usr/bin/pyportify", line 9, in <module>
    load_entry_point('pyportify==0.2.5', 'console_scripts', 'pyportify')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pyportify/server.py", line 5, in <module>
    from pyportify.views import app as application
  File "/usr/lib/python2.7/site-packages/pyportify/views.py", line 76, in <module>
    user_scope = UserScope()
  File "/usr/lib/python2.7/site-packages/pyportify/views.py", line 36, in __init__
    self.spotify_session = spotify.Session(config)
  File "/usr/lib64/python2.7/site-packages/spotify/__init__.py", line 58, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/spotify/session.py", line 60, in __init__
    self.config._sp_session_config, sp_session_ptr))
  File "/usr/lib64/python2.7/site-packages/spotify/error.py", line 31, in maybe_raise
    raise LibError(error_type)
spotify.error.LibError: Unable to open trace file
Exception KeyError: KeyError(139655329145232,) in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored

Now I have looked around for a pointer to what is the problem, but I'm a bit stumped.

**Comment by simonszu** [comment]
I have the same problem on Mac OS Yosemite

**Comment by philtrick** [comment]
Actually, in addition, I tried this on Mac OSX Yosemite, and the same problem occurs.

**Comment by rckclmbr** [comment]
Have a look at #47 it should resolve your issue (reopen if not)
