### ISSUE TITLE
Failed on IOError

### ISSUE THREAD

**Issue by cyrusboadway** [rckclmbr/pyportify#38]
Hello,

I'm running into an error when calling `pyportify-copyall` (and I assume with `pyportify` as well, as that hangs after requesting the transfer, also). It seems to fail in some part of the spotify processing side of things. Any thoughts?

```
Gathering tracks for playlist somelist (12)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b5-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/someuser/.local/lib/python2.7/site-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/home/someuser/.local/lib/python2.7/site-packages/pyportify/google.py", line 64, in find_best_track
    data = self.search_all_access(search_query)
  File "/home/someuser/.local/lib/python2.7/site-packages/pyportify/google.py", line 60, in search_all_access
    data = self._http_get(url)
  File "/home/someuser/.local/lib/python2.7/site-packages/pyportify/google.py", line 90, in _http_get
    res = self._sj_client.get(SJ_URL + url, headers)
  File "/home/someuser/.local/lib/python2.7/site-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/home/someuser/.local/lib/python2.7/site-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/home/someuser/.local/lib/python2.7/site-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/home/someuser/.local/lib/python2.7/site-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
IOError: [Errno 21] Is a directory
<Greenlet at 0x7fa55e776e10: search_gm_track((11, u'spotify:user:1234567890:playlist:0XikmRiePW)> failed with IOError

... repeat 12 times ...
```

**Comment by Saiboogu** [comment]
Encountering the same on Ubuntu 14.04:

```
saiboogu@gravitas:~$ pyportify-copyall
Enter Google email address: saiboogu@gmail.com
Enter Google password:
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
Enter Spotify username: saiboogu
Enter Spotify password:
Gathering tracks for playlist Starred Tracks (198)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 64, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 60, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 90, in _http_get
    res = self._sj_client.get(SJ_URL + url, headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
IOError: [Errno 21] Is a directory
<Greenlet at 0x7f28da466050: search_gm_track((4, 'spotify:user:None:playlist:starred', 'Cake - )> failed with IOError
```

Repeating for each item on each playlist.

**Comment by cimnine** [comment]
Looks like what I'm getting as "AttributeError":

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 207, in search_gm_track
        track = g.find_best_track(search_query)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 64, in find_best_track
        data = self.search_all_access(search_query)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 60, in search_all_access
        data = self._http_get(url)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 90, in _http_get
        res = self._sj_client.get(SJ_URL + url, headers)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 184, in get
        return self.request(METHOD_GET, request_uri, headers=headers)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 172, in request
        block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 286, in __init__
        super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 158, in __init__
        self._read_headers()
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 179, in _read_headers
        self.feed(data)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 118, in _on_header_field
        self._flush_header()
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 133, in _flush_header
        self._headers_index.add(self._current_header_field,
    AttributeError: 'dict' object has no attribute 'add'
    <Greenlet at 0x109553870: search_gm_track((38, u'spotify:user:None:playlist:starred', "Mackl)> failed with AttributeError

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 207, in search_gm_track
        track = g.find_best_track(search_query)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 64, in find_best_track
        data = self.search_all_access(search_query)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 60, in search_all_access
        data = self._http_get(url)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 90, in _http_get
        res = self._sj_client.get(SJ_URL + url, headers)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 184, in get
        return self.request(METHOD_GET, request_uri, headers=headers)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 172, in request
        block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 286, in __init__
        super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 158, in __init__
        self._read_headers()
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 179, in _read_headers
        self.feed(data)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 118, in _on_header_field
        self._flush_header()
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 133, in _flush_header
        self._headers_index.add(self._current_header_field,
    AttributeError: 'dict' object has no attribute 'add'
    <Greenlet at 0x1095537d0: search_gm_track((37, u'spotify:user:None:playlist:starred', 'DJ Fr)> failed with AttributeError

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 207, in search_gm_track
        track = g.find_best_track(search_query)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 64, in find_best_track
        data = self.search_all_access(search_query)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 60, in search_all_access
        data = self._http_get(url)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 90, in _http_get
        res = self._sj_client.get(SJ_URL + url, headers)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 184, in get
        return self.request(METHOD_GET, request_uri, headers=headers)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 172, in request
        block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 286, in __init__
        super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 158, in __init__
        self._read_headers()
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 179, in _read_headers
        self.feed(data)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 118, in _on_header_field
        self._flush_header()
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 133, in _flush_header
        self._headers_index.add(self._current_header_field,
    AttributeError: 'dict' object has no attribute 'add'
    <Greenlet at 0x109553410: search_gm_track((31, u'spotify:user:None:playlist:starred', 'Rudim)> failed with AttributeError

**Comment by J3RI3L** [comment]
Hello all, I've been encountering a similar issue and have had no luck when applying the suggested fixes here. This is what I'm getting, help would be much appreciated.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 64, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 60, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 90, in _http_get
    res = self._sj_client.get(SJ_URL + url, headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
timeout: timed out
<Greenlet at 0xb45d2bbcL: search_gm_track((335, u'spotify:user:j3ri3l:playlist:5M9J6kl6R7axc)> failed with timeout

**Comment by Morabito** [comment]
See https://github.com/rckclmbr/pyportify/pull/39

**Comment by cyrusboadway** [comment]
I'm not sure why this was closed; #39 did not address the bug.

**Comment by rckclmbr** [comment]
4d7dfbd451d4710778fc5afd9f51f0ba0dc7305f resolved the bug you were having

**Comment by rckclmbr** [comment]
The reason was because this code is used in geventhttpclient:

```
import ssl
ssl.get_default_verify_paths().capath
```

for the capath, which was giving "/System/Library/OpenSSL/certs".  Gevent was expecting a filename for cacert, not a path... so I just manually used certifi, which should work just fine.

**Comment by cyrusboadway** [comment]
Confirmed! I'd tested on @wonnage's branch without success, but didn't see your additional commit on master. I'd then run into an API request rate limit of some kind (Spotify seems to simply start timing out after mucking about for too long), but giving it a few hours to relax, all playlists migrated beautifully.

**Comment by cimnine** [comment]
confirmed it's working again. tested on osx.
