### ISSUE TITLE
Unable to Write To Google Playlist

### ISSUE THREAD

**Issue by Morabito** [rckclmbr/pyportify#41]
I am able to grab the tracks from Spotify, but when PyPortify attempts to write to Google, an error occurs.

```Creating in Google Music... 2015-10-23 01:19:06,952 - pyportify.views - ERROR - Exception on /portify/transfer/start [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 136, in transfer_start
    transfer_playlists(lists)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 271, in transfer_playlists
    playlist_id = g.create_playlist(sp_playlist.name)
  File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 73, in create_playlist
    "mutations": mutations,
  File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 105, in _pl_http_post
    headers=headers
TypeError: post() got multiple values for keyword argument 'body'
127.0.0.1 - - [2015-10-23 01:19:07] "POST /portify/transfer/start HTTP/1.1" 500 412 31.401519```

**Comment by rckclmbr** [comment]
This should be resolved, try `pip install --upgrade pyportify==0.2.6`
