### ISSUE TITLE
Issues installing on OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by gravitygun** [rckclmbr/pyportify#42]
When I get to the pip install step, I get:

```
$ pip install pyportify
Collecting pyportify
  Downloading pyportify-0.2.6.tar.gz (866kB)
    100% |████████████████████████████████| 868kB 625kB/s 
Collecting flask>=0.10.1 (from pyportify)
  Downloading Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 544kB 847kB/s 
Collecting Flask-SocketIO>=0.5.0 (from pyportify)
  Downloading Flask-SocketIO-0.6.0.tar.gz
Collecting gunicorn==0.16.1 (from pyportify)
  Downloading gunicorn-0.16.1.tar.gz (344kB)
    100% |████████████████████████████████| 348kB 1.0MB/s 
Collecting pyspotify>=2.0.0b5 (from pyportify)
  Downloading pyspotify-2.0.5-cp27-none-macosx_10_6_intel.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 203kB/s 
Collecting six>=1.6.1 (from pyportify)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting gevent==1.0.2 (from pyportify)
  Downloading gevent-1.0.2-cp27-none-macosx_10_11_intel.whl (559kB)
    100% |████████████████████████████████| 561kB 639kB/s 
Collecting geventhttpclient==1.2.0 (from pyportify)
  Downloading geventhttpclient-1.2.0.tar.gz
Collecting gpsoauth==0.0.1 (from pyportify)
  Downloading gpsoauth-0.0.1.tar.gz
Collecting certifi (from pyportify)
  Downloading certifi-2015.9.6.2-py2.py3-none-any.whl (371kB)
    100% |████████████████████████████████| 372kB 806kB/s 
Collecting Werkzeug>=0.7 (from flask>=0.10.1->pyportify)
  Downloading Werkzeug-0.10.4-py2.py3-none-any.whl (293kB)
    100% |████████████████████████████████| 294kB 1.1MB/s 
Collecting Jinja2>=2.4 (from flask>=0.10.1->pyportify)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 927kB/s 
Collecting itsdangerous>=0.21 (from flask>=0.10.1->pyportify)
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 49kB 1.4MB/s 
Collecting gevent-socketio>=0.3.6 (from Flask-SocketIO>=0.5.0->pyportify)
  Downloading gevent_socketio-0.3.6-py27-none-any.whl
Collecting cffi>=1.0.0 (from pyspotify>=2.0.0b5->pyportify)
  Downloading cffi-1.3.0-cp27-none-macosx_10_10_intel.whl (192kB)
    100% |████████████████████████████████| 192kB 1.1MB/s 
Collecting greenlet>=0.4.7 (from gevent==1.0.2->pyportify)
  Downloading greenlet-0.4.9.tar.gz (54kB)
    100% |████████████████████████████████| 57kB 1.7MB/s 
Collecting pycrypto (from gpsoauth==0.0.1->pyportify)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 446kB 769kB/s 
Collecting requests (from gpsoauth==0.0.1->pyportify)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 668kB/s 
Collecting MarkupSafe (from Jinja2>=2.4->flask>=0.10.1->pyportify)
  Downloading MarkupSafe-0.23.tar.gz
Collecting gevent-websocket (from gevent-socketio>=0.3.6->Flask-SocketIO>=0.5.0->pyportify)
  Downloading gevent-websocket-0.9.5.tar.gz
Collecting pycparser (from cffi>=1.0.0->pyspotify>=2.0.0b5->pyportify)
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 1.6MB/s 
Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, flask, greenlet, gevent, gevent-websocket, gevent-socketio, Flask-SocketIO, gunicorn, pycparser, cffi, pyspotify, six, certifi, geventhttpclient, pycrypto, requests, gpsoauth, pyportify
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/wheel.py", line 310, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 71, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/werkzeug'
```

If I try again with sudo -H:

```
$ sudo -H pip install pyportify
Password:
Collecting pyportify
  Downloading pyportify-0.2.6.tar.gz (866kB)
    100% |████████████████████████████████| 868kB 583kB/s 
Requirement already satisfied (use --upgrade to upgrade): flask>=0.10.1 in /Library/Python/2.7/site-packages (from pyportify)
Collecting Flask-SocketIO>=0.5.0 (from pyportify)
  Downloading Flask-SocketIO-0.6.0.tar.gz
Collecting gunicorn==0.16.1 (from pyportify)
  Downloading gunicorn-0.16.1.tar.gz (344kB)
    100% |████████████████████████████████| 348kB 1.1MB/s 
Collecting pyspotify>=2.0.0b5 (from pyportify)
  Downloading pyspotify-2.0.5-cp27-none-macosx_10_6_intel.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 262kB/s 
Collecting six>=1.6.1 (from pyportify)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting gevent==1.0.2 (from pyportify)
  Downloading gevent-1.0.2-cp27-none-macosx_10_11_intel.whl (559kB)
    100% |████████████████████████████████| 561kB 617kB/s 
Collecting geventhttpclient==1.2.0 (from pyportify)
  Downloading geventhttpclient-1.2.0.tar.gz
Collecting gpsoauth==0.0.1 (from pyportify)
  Downloading gpsoauth-0.0.1.tar.gz
Collecting certifi (from pyportify)
  Downloading certifi-2015.9.6.2-py2.py3-none-any.whl (371kB)
    100% |████████████████████████████████| 372kB 1.4MB/s 
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /Library/Python/2.7/site-packages (from flask>=0.10.1->pyportify)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /Library/Python/2.7/site-packages (from flask>=0.10.1->pyportify)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from flask>=0.10.1->pyportify)
Collecting gevent-socketio>=0.3.6 (from Flask-SocketIO>=0.5.0->pyportify)
  Downloading gevent_socketio-0.3.6-py27-none-any.whl
Collecting cffi>=1.0.0 (from pyspotify>=2.0.0b5->pyportify)
  Downloading cffi-1.3.0-cp27-none-macosx_10_10_intel.whl (192kB)
    100% |████████████████████████████████| 192kB 1.3MB/s 
Collecting greenlet>=0.4.7 (from gevent==1.0.2->pyportify)
  Downloading greenlet-0.4.9.tar.gz (54kB)
    100% |████████████████████████████████| 57kB 6.1MB/s 
Collecting pycrypto (from gpsoauth==0.0.1->pyportify)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 446kB 660kB/s 
Collecting requests (from gpsoauth==0.0.1->pyportify)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 646kB/s 
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Library/Python/2.7/site-packages (from Jinja2>=2.4->flask>=0.10.1->pyportify)
Collecting gevent-websocket (from gevent-socketio>=0.3.6->Flask-SocketIO>=0.5.0->pyportify)
  Downloading gevent-websocket-0.9.5.tar.gz
Collecting pycparser (from cffi>=1.0.0->pyspotify>=2.0.0b5->pyportify)
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 1.7MB/s 
Installing collected packages: greenlet, gevent, gevent-websocket, gevent-socketio, Flask-SocketIO, gunicorn, pycparser, cffi, pyspotify, six, certifi, geventhttpclient, pycrypto, requests, gpsoauth, pyportify
  Running setup.py install for greenlet
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-r389iQ/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PaQRWe-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.macosx-10.11-intel-2.7
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c greenlet.c -o build/temp.macosx-10.11-intel-2.7/greenlet.o
    creating build/lib.macosx-10.11-intel-2.7
    cc -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.11-intel-2.7/greenlet.o -o build/lib.macosx-10.11-intel-2.7/greenlet.so
    running install_lib
    copying build/lib.macosx-10.11-intel-2.7/greenlet.so -> /Library/Python/2.7/site-packages
    running install_headers
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet': Operation not permitted
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-r389iQ/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PaQRWe-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-r389iQ/greenlet
```

Please help! :-)

**Comment by Tacticalwombat** [comment]
Mine did that but all I needed to do to fix it was to install python to get the updates I guess. I'm not a developer haha I'm just trying to get this to work
>brew install python

**Comment by ConnerStephens** [comment]
For me, I realized I was trying to install Python(2)/(3) with Homebrew. Homebrew packages Python(2) with version 2.7.10, and upon further discover, OS X 10.11 comes stock with 2.7.10! The fix I found for pip was: 

sudo pip install pbr
sudo pip install --no-deps stevedore

**Comment by ConnerStephens** [comment]
I had the same issue too. I realized instal python from Homebrew was useless because Homebrew's version of Python(2) was 2.7.10, but OS X 10.11 comes stock with 2.7.10 so it was not handling it well. 
I also did this too once I installed Python(3) and things have been smooth ever since:

sudo pip install pbr
sudo pip install --no-deps stevedore
sudo pip install --no-deps virtualenvwrapper


source: http://stackoverflow.com/questions/32086631/cant-install-virtualenvwrapper-on-osx-10-11-el-capitan

**Comment by gravitygun** [comment]
Thanks guys. I did "brew install python" and also the three "sudo pip install" @ConnerStephens mentioned. pyportify is apparently installed, but now I get the following:

```
$ pyportify
Traceback (most recent call last):
  File "/usr/local/bin/pyportify", line 7, in <module>
    from pyportify.server import main
  File "/usr/local/lib/python2.7/site-packages/pyportify/server.py", line 5, in <module>
    from pyportify.views import app as application
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 10, in <module>
    from socketio import socketio_manage
ImportError: cannot import name socketio_manage
Exception KeyError: KeyError(4325155056,) in <module 'threading' from '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
```

I really have no idea why it is unable to find socketio_manage... any clues?

**Comment by stepri** [comment]
Same problem here as @gravitygun.

**Comment by achint-s** [comment]
Hey @gravitygun I had this issue as well.. Fixed by installing socketio.

pip install gevent-socketio

**Comment by joesanford** [comment]
Is there a way to get this working on El Capitan without updating to python 3?

**Comment by achint-s** [comment]
It's working fine for me on El Capitan. The only thing I had to add was 
pip install gevent-socketio

**Comment by jagrat** [comment]
I tried all these ways ... Still keep getting " error error: command '/usr/bin/clang' failed with exit status 1". Any idea what's wrong ?

```running install

running build

running build_py

creating build

creating build/lib.macosx-10.6-intel-2.7

creating build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/__init__.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/_ssl2.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/_sslgte279.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/_threading.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/backdoor.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/baseserver.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/coros.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/event.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/fileobject.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/greenlet.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/hub.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/local.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/lock.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/monkey.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/os.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/pool.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/pywsgi.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/queue.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/resolver_ares.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/resolver_thread.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/select.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/server.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/socket.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/ssl.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/subprocess.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/thread.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/threading.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/threadpool.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/timeout.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/util.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/win32util.py -> build/lib.macosx-10.6-intel-2.7/gevent

copying gevent/wsgi.py -> build/lib.macosx-10.6-intel-2.7/gevent

running build_ext

Running '/bin/sh /private/var/folders/_x/81s0n6j17tz5m0fzhyvn5c6r0000gn/T/pip_build_Jagrat/gevent/libev/configure > configure-output.txt' in /private/var/folders/_x/81s0n6j17tz5m0fzhyvn5c6r0000gn/T/pip_build_Jagrat/gevent/build/temp.macosx-10.6-intel-2.7/libev

building 'gevent.core' extension

creating build/temp.macosx-10.6-intel-2.7/gevent

/usr/bin/clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -U__llvm__ -Qunused-arguments -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.macosx-10.6-intel-2.7/libev -Ilibev -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gevent/gevent.core.c -o build/temp.macosx-10.6-intel-2.7/gevent/gevent.core.o

In file included from gevent/gevent.core.c:249:

In file included from gevent/libev.h:2:

libev/ev.c:483:48: warning: '/*' within block comment [-Wcomment]

/*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */

                                               ^

libev/ev.c:1029:42: error: '_Noreturn' keyword must precede function declarator

  ecb_inline void ecb_unreachable (void) ecb_noreturn;

                                         ^~~~~~~~~~~~

  _Noreturn

libev/ev.c:832:26: note: expanded from macro 'ecb_noreturn'

  #define ecb_noreturn   _Noreturn

                         ^

libev/ev.c:1625:31: warning: 'extern' variable has an initializer [-Wextern-initializer]

  EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */

                              ^

libev/ev.c:1796:7: warning: unused variable 'ocur_' [-Wunused-variable]

      array_needsize (ANPENDING, pendings [pri], pendingmax [pri], w_->pending, EMPTY2);

      ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

libev/ev.c:1807:3: warning: unused variable 'ocur_' [-Wunused-variable]

  array_needsize (W, rfeeds, rfeedmax, rfeedcnt + 1, EMPTY2);

  ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

libev/ev.c:1934:7: warning: unused variable 'ocur_' [-Wunused-variable]

      array_needsize (int, fdchanges, fdchangemax, fdchangecnt, EMPTY2);

      ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

In file included from gevent/gevent.core.c:249:

In file included from gevent/libev.h:2:

In file included from libev/ev.c:2484:

libev/ev_kqueue.c:50:3: warning: unused variable 'ocur_' [-Wunused-variable]

  array_needsize (struct kevent, kqueue_changes, kqueue_changemax, kqueue_changecnt, EMPTY2);

  ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

In file included from gevent/gevent.core.c:249:

In file included from gevent/libev.h:2:

In file included from libev/ev.c:2490:

libev/ev_poll.c:66:7: warning: unused variable 'ocur_' [-Wunused-variable]

      array_needsize (struct pollfd, polls, pollmax, pollcnt, EMPTY2);

      ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

libev/ev.c:3648:34: warning: '&' within '|' [-Wbitwise-op-parentheses]

  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);

                       ~~~~~~~~~~^~~~~~~~~~~~~ ~

libev/ev.c:3648:34: note: place parentheses around the '&' expression to silence this warning

  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);

                                 ^

                       (                      )

libev/ev.c:3687:3: warning: unused variable 'ocur_' [-Wunused-variable]

  array_needsize (ANHE, timers, timermax, ev_active (w) + 1, EMPTY2);

  ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

libev/ev.c:4367:5: warning: unused variable 'ocur_' [-Wunused-variable]

    array_needsize (ev_idle *, idles [ABSPRI (w)], idlemax [ABSPRI (w)], active, EMPTY2);

    ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

libev/ev.c:4407:3: warning: unused variable 'ocur_' [-Wunused-variable]

  array_needsize (ev_prepare *, prepares, preparemax, preparecnt, EMPTY2);

  ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

libev/ev.c:4445:3: warning: unused variable 'ocur_' [-Wunused-variable]

  array_needsize (ev_check *, checks, checkmax, checkcnt, EMPTY2);

  ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

libev/ev.c:4592:3: warning: unused variable 'ocur_' [-Wunused-variable]

  array_needsize (ev_fork *, forks, forkmax, forkcnt, EMPTY2);

  ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

libev/ev.c:4675:3: warning: unused variable 'ocur_' [-Wunused-variable]

  array_needsize (ev_async *, asyncs, asyncmax, asynccnt, EMPTY2);

  ^

libev/ev.c:1758:22: note: expanded from macro 'array_needsize'

      int ecb_unused ocur_ = (cur);                                     \

                     ^

14 warnings and 1 error generated.

error: command '/usr/bin/clang' failed with exit status 1```

**Comment by rckclmbr** [comment]
@jagrat try this:

  CFLAGS='-std=c99' pip install gevent==1.0.2

(from https://github.com/gevent/gevent/issues/656#issuecomment-142813358)

**Comment by rckclmbr** [comment]
Removed dependency on gevent, this should be resolved now.

**Comment by MgMgPyaeSoneWin** [comment]
You don't have rw permission to the directories. Assuming you have administrator rights, you can change the permissions with sudo chown -R $USER /absolute/path/to/directory. If you're running OS X 10.11+, you'll probably also need disable the System Integrity Protection, but don't forget to reenable it after you're done (just to be safe).

sudo chown -R $USER /usr/local/lib/python2.7/
