### ISSUE TITLE
Gmail Logon Error

### ISSUE THREAD

**Issue by Tacticalwombat** [rckclmbr/pyportify#43]
[29/Oct/2015:16:12:05] ENGINE Bus STARTING
[29/Oct/2015:16:12:05] ENGINE Started monitor thread 'Autoreloader'.
[29/Oct/2015:16:12:05] ENGINE Started monitor thread '_TimeoutMonitor'.
[29/Oct/2015:16:12:06] ENGINE Serving on http://0.0.0.0:3132
[29/Oct/2015:16:12:06] ENGINE Bus STARTED
/usr/local/lib/python2.7/site-packages/pyportify/static
2015-10-29 16:12:22 [7138] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /google/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 68, in google_login
    user_scope.google_login(email, password)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
2015-10-29 16:12:23 [7138] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /google/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 68, in google_login
    user_scope.google_login(email, password)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
2015-10-29 16:12:29 [7138] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /google/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 68, in google_login
    user_scope.google_login(email, password)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
2015-10-29 16:12:30 [7138] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /google/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 68, in google_login
    user_scope.google_login(email, password)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
2015-10-29 16:12:30 [7138] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /google/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 68, in google_login
    user_scope.google_login(email, password)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
2015-10-29 16:12:30 [7138] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /google/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 68, in google_login
    user_scope.google_login(email, password)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
2015-10-29 16:12:30 [7138] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /google/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 68, in google_login
    user_scope.google_login(email, password)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
2015-10-29 16:12:31 [7138] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /google/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 68, in google_login
    user_scope.google_login(email, password)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)

When I put in my password and hit enter no dialog box pops up and nothing happens but the Terminal reads this.

Any suggestions?

**Comment by ConnerStephens** [comment]
I might be wrong, but it is worth a try. You might have to go into your Gmail account and edit the security settings to turn on the "Allow less secure apps" option.

**Comment by axolx** [comment]
Setting the Google account security to "Allow less secure apps" solved the issue for me. Just make sure to undo the chance after the migration. This is an awesome project and so easy to run w/ docker. Thank you!

**Comment by Tacticalwombat** [comment]
I did that, but it didn't seem to work.

I tried using
>pyportify-copyall

But that gave me
>Traceback (most recent call last):
  File "/usr/local/bin/pyportify-copyall", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pyportify/copy_all.py", line 23, in main
    app.user_scope.google_login(google_email, google_pass)
  File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 41, in google_login
    self._google_loggedin = self.googleapi.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)

**Comment by rckclmbr** [comment]
Try latest version.  This has been completely rewritten.
