### ISSUE TITLE
Error running PyPortify

### ISSUE THREAD

**Issue by waltm78** [rckclmbr/pyportify#46]
I am running Ubuntu 14.04 in a VM on Windows 10.  I followed the instructions to install Pyportify via terminal and when I run pyportify or pyportify-copyall i get the following:

Traceback (most recent call last):
  File "/usr/local/bin/pyportify", line 9, in <module>
    load_entry_point('pyportify==0.2.7', 'console_scripts', 'pyportify')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pyportify/server.py", line 5, in <module>
    from pyportify.views import app as application
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 10, in <module>
    from socketio import socketio_manage
ImportError: cannot import name socketio_manage
Exception KeyError: KeyError(139971929585296,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

I checked to see that socketio_manage was installed and updated.  Any clue?

Thx

**Comment by rckclmbr** [comment]
See #47 -- it has more information.
