### ISSUE TITLE
Exception KeyError: KeyError(139655329145232,) in ignored

### ISSUE THREAD

**Issue by uelitonjunior** [rckclmbr/pyportify#47]
Hi!

I installed using a Ubuntu 15.10 VM and i'm getting this error:

user@ubuntu-vm:~$ pyportify
Traceback (most recent call last):
  File "/usr/local/bin/pyportify", line 9, in <module>
    load_entry_point('pyportify==0.2.7', 'console_scripts', 'pyportify')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/server.py", line 5, in <module>
    from pyportify.views import app as application
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 10, in <module>
    from socketio import socketio_manage
ImportError: cannot import name socketio_manage
Exception KeyError: KeyError(139912956678224,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by fuadsaud** [comment]
As per: https://github.com/miguelgrinberg/Flask-SocketIO/issues/69

running it inside a virtualenv should make it work.

**Comment by timedroid** [comment]
Try running "sudo pip install -Iv Flask-SocketIO==0.5.0" to downgrade to an older version of Flask-SocketIO.

**Comment by svict4** [comment]
That did the trick @timedroid

**Comment by rckclmbr** [comment]
Removed dependency on flask-socketio, this should be resolved.
