### ISSUE TITLE
AttributeError: 'module' object has no attribute 'patch_all'

### ISSUE THREAD

**Issue by thlengane** [rckclmbr/pyportify#51]
Hi,

I am getting the error below when I execute, please help.
This is on Linux Mint

my@machine ~ $ pyportify
Traceback (most recent call last):
  File "/usr/local/bin/pyportify", line 9, in <module>
    load_entry_point('pyportify==0.2.7', 'console_scripts', 'pyportify')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pyportify/server.py", line 5, in <module>
    from pyportify.views import app as application
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 7, in <module>
    monkey.patch_all()
AttributeError: 'module' object has no attribute 'patch_all'

**Comment by thlengane** [comment]
Never mind, sorted. Don't know what I did to fix it.
