### ISSUE TITLE
Failed with SSLError

### ISSUE THREAD

**Issue by thlengane** [rckclmbr/pyportify#52]
I have somehow did everything right but to transfer the playlist. I am getting some sslerror and don't know how to fix this, please help..

Here are my full logs below:-

my@linux ~ $ pyportify
Open your browser and go to http://localhost:3132

Managing socket.io
Socketio session started
New connection
Managing socket.io
Socketio session started
New connection
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
127.0.0.1 - - [2015-12-09 16:09:22] "POST /google/login HTTP/1.1" 200 157 0.801953
Client disconnected
Client disconnected
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
127.0.0.1 - - [2015-12-09 16:09:56] "POST /google/login HTTP/1.1" 200 161 1.740417

127.0.0.1 - - [2015-12-09 16:11:28] "POST /spotify/login HTTP/1.1" 200 161 1.297684
127.0.0.1 - - [2015-12-09 16:11:28] "GET /spotify/playlists HTTP/1.1" 200 2746 0.003640
Gathering tracks for playlist Starred (11)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241dd6230: search_gm_track((6, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241dd6550: search_gm_track((3, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241f48c30: search_gm_track((1, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241dd6f50: search_gm_track((8, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241dd6870: search_gm_track((2, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241dd6eb0: search_gm_track((7, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241dd6190: search_gm_track((5, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241dd6410: search_gm_track((4, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9240d35050: search_gm_track((9, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9241f48f50: search_gm_track((0, u'spotify:user:imspotify:playlist:52zixsiq41at)> failed with SSLError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 207, in search_gm_track
    track = g.find_best_track(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 67, in find_best_track
    data = self.search_all_access(search_query)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 63, in search_all_access
    data = self._http_get(url)
  File "/usr/local/lib/python2.7/dist-packages/pyportify/google.py", line 95, in _http_get
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 184, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 157, in request
    sock = self._connection_pool.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._create_socket()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/connectionpool.py", line 116, in _create_socket
    raise first_error
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<Greenlet at 0x7f9240d350f0: search_gm_track((10, u'spotify:user:imspotify:playlist:52zixsiq41a)> failed with SSLError

127.0.0.1 - - [2015-12-09 16:12:09] "POST /portify/transfer/start HTTP/1.1" 200 164 5.504931

**Comment by markhouston72** [comment]
thlengane, did you find a solution for this? I am having the same problem.

**Comment by thlengane** [comment]
@markhouston72 Yes, I did. The solution is right here..https://github.com/rckclmbr/pyportify/issues/49

**Comment by markhouston72** [comment]
Thanks for pointing me in the right direction to the solution that worked for you, I hadn't put 2 + 2 together and linked the 2 solutions but I have tried #49 already and it didn't work in my case. Back to the drawing board :(
