### ISSUE TITLE
[OSX] Crashes immediately on running: AttributeError and KeyError

### ISSUE THREAD

**Issue by joewbrown** [rckclmbr/pyportify#56]
Installation all goes fine on Yosemite but then this happens:
```
bash-3.2$ pyportify
Traceback (most recent call last):
  File "/usr/local/bin/pyportify", line 9, in <module>
    load_entry_point('pyportify==0.2.9', 'console_scripts', 'pyportify')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/pyportify/server.py", line 5, in <module>
    from pyportify.views import app as application
  File "/Library/Python/2.7/site-packages/pyportify/views.py", line 76, in <module>
    user_scope = UserScope()
  File "/Library/Python/2.7/site-packages/pyportify/views.py", line 31, in __init__
    self.googleapi = Mobileclient()
  File "/Library/Python/2.7/site-packages/pyportify/google.py", line 30, in __init__
    "ca_certs": certifi.old_where(),
AttributeError: 'module' object has no attribute 'old_where'
Exception KeyError: KeyError(4539898928,) in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
```

Any suggestions?

**Comment by rckclmbr** [comment]
I just released a new version.  Would you care to give it a try?  You can download a binary at https://xr6.me/pyportify/pyportify-0.3.0-osx.zip
