### ISSUE TITLE
Unable to sign in to Google from pyportify when using Chrome

### ISSUE THREAD

**Issue by LovedByTheLord** [rckclmbr/pyportify#61]
Hi,

I'm on Windows trying to sign in to Google.  The following error is displayed in the pyportify.exe console window when I click the Submit button.

Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\app.py", line 36, in google_login
  File "site-packages\aiohttp\web_reqrep.py", line 334, in json
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This only seems to happen in Chrome.  If I do the same thing in IE, it works fine.

**Comment by Peleg** [comment]
fwiw i just ran into the same issue when trying to log in w/ 2-step verification turned on on my goog account. turning it off seemed to solve the issue for me.

**Comment by russjr08** [comment]
Hmm, I had no problems with 2FA, but I used an app password for pyportify.

**Comment by Tsarpf** [comment]
Don't turn off your 2-step for this. Use app passwords like russjr08 said https://security.google.com/settings/security/apppasswords

**Comment by DavidEscalante** [comment]
Why people keep recommending that Google app password? The link leads to nowhere.

**Comment by russjr08** [comment]
Do you have 2FA enabled for sure? It takes me to the proper page. 

I'd upload a screenshot but I'm on mobile and am a bit too lazy to find somewhere to upload it at the moment :P try searching "Google App Password" on Google.

**Comment by mmuneebs** [comment]
I had to enable 2FA first, and then generate the app password for this to work. It did NOT work without 2FA. There's no option to create an App pass while 2FA is turned off.
