### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by robertbaker** [rckclmbr/pyportify#65]
```Listening on http://0.0.0.0:3132
Please open your browser window to http://localhost:3132
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbaker\\AppData\\Local\\Temp\\_MEI148282\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbaker\\AppData\\Local\\Temp\\_MEI148282\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbaker\\AppData\\Local\\Temp\\_MEI148282\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbaker\\AppData\\Local\\Temp\\_MEI148282\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbaker\\AppData\\Local\\Temp\\_MEI148282\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\app.py", line 108, in transfer_start
  File "pyportify\app.py", line 131, in transfer_playlists
  File "pyportify\spotify.py", line 76, in fetch_playlist_tracks
  File "pyportify\spotify.py", line 70, in fetch_saved_tracks
  File "pyportify\spotify.py", line 60, in _http_get_all
  File "pyportify\spotify.py", line 122, in _http_get
Exception: Error: {'error': {'status': 502, 'message': 'Bad gateway.'}}, url: https://api.spotify.com/v1/me/tracks?offset=140&limit=20
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbaker\\AppData\\Local\\Temp\\_MEI148282\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbaker\\AppData\\Local\\Temp\\_MEI148282\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbaker\\AppData\\Local\\Temp\\_MEI148282\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\app.py", line 108, in transfer_start
  File "pyportify\app.py", line 131, in transfer_playlists
  File "pyportify\spotify.py", line 76, in fetch_playlist_tracks
  File "pyportify\spotify.py", line 70, in fetch_saved_tracks
  File "pyportify\spotify.py", line 60, in _http_get_all
  File "pyportify\spotify.py", line 122, in _http_get
Exception: Error: {'error': {'status': 502, 'message': 'Bad gateway.'}}, url: https://api.spotify.com/v1/me/tracks?offset=60&limit=20```

**Comment by nwaywood** [comment]
I am having the same issue (trying to use the copyall command), here is my stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyportify-copyall", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pyportify/copy_all.py", line 61, in main
    loop.run_until_complete(start())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/site-packages/pyportify/copy_all.py", line 55, in start
    yield from app.transfer_playlists(None, session, s, g, playlists)
  File "/usr/local/lib/python3.5/site-packages/pyportify/app.py", line 131, in transfer_playlists
    sp_playlist_tracks = yield from s.fetch_playlist_tracks(d_list["uri"])
  File "/usr/local/lib/python3.5/site-packages/pyportify/spotify.py", line 76, in fetch_playlist_tracks
    ret = yield from self.fetch_saved_tracks()
  File "/usr/local/lib/python3.5/site-packages/pyportify/spotify.py", line 70, in fetch_saved_tracks
    tracks = yield from self._http_get_all(url)
  File "/usr/local/lib/python3.5/site-packages/pyportify/spotify.py", line 60, in _http_get_all
    data = yield from self._http_get(url)
  File "/usr/local/lib/python3.5/site-packages/pyportify/spotify.py", line 122, in _http_get
    raise Exception("Error: {0}, url: {1}".format(data, url))
Exception: Error: {'error': {'status': 502, 'message': 'Bad gateway.'}}, url: https://api.spotify.com/v1/me/tracks?offset=20&limit=20
```

**Comment by nwaywood** [comment]
Update: 

I tried this again today and everything worked :) 

I guess the bad gateway error must have been a problem and spotify's end, seems its fixed now

**Comment by rckclmbr** [comment]
Great to hear, I was thinking this might be the case.  Yea, this sounded like a proxy issue on their side, glad you could confirm.
