### ISSUE TITLE
Getting Error on Launch, may be leading to halt in the midst of finding songs.

### ISSUE THREAD

**Issue by S33V** [rckclmbr/pyportify#68]
When launching pyportify.exe on my Windows 8.1 machine I immediatly get this error:
```
Listening on http://0.0.0.0:3132
Please open your browser window to http://localhost:3132
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod
03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SEVERI~1\\Ap
pData\\Local\\Temp\\_MEI41602\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod
03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SEVERI~1\\Ap
pData\\Local\\Temp\\_MEI41602\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 544, in
 urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 341, in
 _make_request
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 761, in
 _validate_conn
  File "site-packages\requests\packages\urllib3\connection.py", line 204, in con
nect
  File "site-packages\requests\packages\urllib3\connection.py", line 134, in _ne
w_conn
  File "site-packages\requests\packages\urllib3\util\connection.py", line 64, in
 create_connection
  File "socket.py", line 732, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 370, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 597, in
 urlopen
  File "site-packages\requests\packages\urllib3\util\retry.py", line 245, in inc
rement
  File "site-packages\requests\packages\urllib3\packages\six.py", line 309, in r
eraise
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 544, in
 urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 341, in
 _make_request
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 761, in
 _validate_conn
  File "site-packages\requests\packages\urllib3\connection.py", line 204, in con
nect
  File "site-packages\requests\packages\urllib3\connection.py", line 134, in _ne
w_conn
  File "site-packages\requests\packages\urllib3\util\connection.py", line 64, in
 create_connection
  File "socket.py", line 732, in getaddrinfo
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', gaie
rror(11001, 'getaddrinfo failed'))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\app.py", line 43, in google_login
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\google.py", line 27, in login
  File "pyportify\gpsoauth\__init__.py", line 65, in perform_master_login
  File "pyportify\gpsoauth\__init__.py", line 21, in _perform_auth_request
  File "site-packages\requests\api.py", line 109, in post
  File "site-packages\requests\api.py", line 50, in request
  File "site-packages\requests\sessions.py", line 465, in request
  File "site-packages\requests\sessions.py", line 573, in send
  File "site-packages\requests\adapters.py", line 415, in send
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(11001, 'ge
taddrinfo failed'))
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod
03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SEVERI~1\\Ap
pData\\Local\\Temp\\_MEI41602\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod
03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SEVERI~1\\Ap
pData\\Local\\Temp\\_MEI41602\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\pyportify\virt\lib\site-packages\PyInstaller\loader\pyimod
03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SEVERI~1\\Ap
pData\\Local\\Temp\\_MEI41602\\pyportify\\favicon.ico'
````

I've had the halt happen at different times, i.e. 92 vs 123 tracks found

**Comment by S33V** [comment]
I'm attempting to run the .exe as administrator...
I received the same errors and it halted at track 88

**Comment by S33V** [comment]
It might be my network, switching networks and attempting again.

**Comment by S33V** [comment]
I was able to (semi)successfully import a smaller playlist (103 songs). It only searched through 93 of the 103 songs. It was successfuly able to find 92 and could not find 1.

**Comment by rckclmbr** [comment]
I added throttling, that will most likely resolve this problem.
