### ISSUE TITLE
Issue when running docker instance

### ISSUE THREAD

**Issue by bennimmo** [rckclmbr/pyportify#7]
# docker run -t -i --rm rckclmbr/pyportify /ve/bin/pyportify-copyall
Unable to find image 'rckclmbr/pyportify' locally
Pulling repository rckclmbr/pyportify
c63d3a21f646: Download complete 
511136ea3c5a: Download complete 
3b363fd9d7da: Download complete 
607c5d1cca71: Download complete 
f62feddc05dc: Download complete 
8eaa4ff06b53: Download complete 
69a6b88af78b: Download complete 
2de95f27f7e7: Download complete 
021587cb218f: Download complete 
02e20e6af814: Download complete 
d74517819d5d: Download complete 
98ee62334272: Download complete 
d784e128bba4: Download complete 
7b0fe952792a: Download complete 
d009e392a431: Download complete 
e5207406dd29: Download complete 
Traceback (most recent call last):
  File "/ve/bin/pyportify-copyall", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2970, in <module>
    working_set = WorkingSet._build_master()
  File "/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 761, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six>=1.6.1

**Comment by rckclmbr** [comment]
Should be fixed, just ```docker pull rckclmbr/pyportify``` and run again

**Comment by bennimmo** [comment]
Yeah all seems fixed in the docker version now
