### ISSUE TITLE
Won't transfer playlist

### ISSUE THREAD

**Issue by projectglue** [rckclmbr/pyportify#75]
Hi there,

I am getting stuck at step 4 and it wont transfer the playlists, it looks like the page is stuck.
This is the second time I've tried this.

Listening on http://0.0.0.0:3132
Please open your browser window to http://localhost:3132
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ANGELI~1.LEP\\AppData\\Local\\Temp\\_MEI99082\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ANGELI~1.LEP\\AppData\\Local\\Temp\\_MEI99082\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\app.py", line 111, in transfer_start
  File "pyportify\app.py", line 135, in transfer_playlists
  File "pyportify\spotify.py", line 78, in fetch_playlist_tracks
  File "pyportify\spotify.py", line 72, in fetch_saved_tracks
  File "pyportify\spotify.py", line 62, in _http_get_all
  File "pyportify\spotify.py", line 124, in _http_get
Exception: Error: {'error': {'status': 403, 'message': 'Insufficient client scope'}}, url: https://api.spotify.com/v1/me/tracks

**Comment by rckclmbr** [comment]
Make sure you checked all the boxes when getting your spotify key
