### ISSUE TITLE
Cannot login to Google via Chrome on Windows

### ISSUE THREAD

**Issue by mordhau5** [rckclmbr/pyportify#77]
Email and PW confirmed can log into Play Music.

Windows 10 64bit Home edition with Chrome Version 53.0.2785.143 m
<img src="http://puu.sh/rzOwX/97be78a1a2.png">

From terminal: `Listening on http://0.0.0.0:3132
Please open your browser window to http://localhost:3132
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Carl\\AppData\\Local\\Temp\\_MEI125042\\pyportify\\favicon.ico'
Error handling request
Traceback (most recent call last):
  File "site-packages\aiohttp\server.py", line 266, in start
  File "site-packages\aiohttp\web.py", line 90, in handle_request
  File "pyportify\dispatcher.py", line 68, in static_view
  File "asyncio\coroutines.py", line 206, in coro
  File "pyportify\dispatcher.py", line 52, in handle
  File "pkgutil.py", line 629, in get_data
  File "c:\users\josh\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Carl\\AppData\\Local\\Temp\\_MEI125042\\pyportify\\favicon.ico'
`

**Comment by mordhau5** [comment]
Sorry, I thought I had already disabled 2fa but it didn't take. Tried again and it was good.
