### ISSUE TITLE
Error when converting playlist

### ISSUE THREAD

**Issue by ScheerMT** [rckclmbr/pyportify#8]
Install on Apple Yosemite using the instructions provided. Install was successful. When trying to convert a playlist the following errors were received in the terminal window:
```
[17/Jan/2015:20:36:41] ENGINE Bus STARTING
[17/Jan/2015:20:36:41] ENGINE Started monitor thread 'Autoreloader'.
[17/Jan/2015:20:36:41] ENGINE Started monitor thread '_TimeoutMonitor'.
[17/Jan/2015:20:36:41] ENGINE Serving on http://0.0.0.0:3132
[17/Jan/2015:20:36:41] ENGINE Bus STARTED
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyportify/static
2015-01-17 20:38:13 [49203] [WARNING] base.py:143:get_response Not Found: /socket.io/1/
Gathering tracks for playlist Play it forward
2015-01-17 20:38:14 [49203] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /portify/transfer/start
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyportify/views.py", line 113, in transfer_start
    transfer_playlists(lists)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyportify/views.py", line 163, in transfer_playlists
    search_results = g.search_all_access(search_query, max_results=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 796, in search_all_access
    res = self._make_call(mobileclient.Search, query, max_results)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 225, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: Search: 404 Client Error: Not Found
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'A Tribe Called Red - Electric Pow Wow Drum', 'max-results': 1}, 'method': 'GET'})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "notFound",\n    "message": "Not Found"\n   }\n  ],\n  "code": 404,\n  "message": "Not Found"\n }\n}\n')
```

I will continue to try different playlists and see if similar errors occur

EDIT:

I realized i didn't have Google Music All Access enabled. After enabling this worked perfectly fine!

**Comment by anmary** [comment]
I have the same issue with all access enabled.

``` 
(4535/5306) Found 'Dean Wareham - I Can Only Give My All' in Google Music
2015-02-02 09:07:05 [1217] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /portify/transfer/start
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyportify/views.py", line 114, in transfer_start
    transfer_playlists(lists)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyportify/views.py", line 166, in transfer_playlists
    search_results = g.search_all_access(search_query, max_results=1)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 796, in search_all_access
    res = self._make_call(mobileclient.Search, query, max_results)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 225, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: Search: 500 Server Error: Internal Server Error
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'Dean Wareham - Babes in the Woods', 'max-results': 1}, 'method': 'GET'})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "internalError",\n    "message": "Internal Error"\n   }\n  ],\n  "code": 500,\n  "message": "Internal Error"\n }\n}\n')
```

**Comment by ScheerMT** [comment]
hmm. your error was an error code 500. I would try running the script again later and see if the same error continues to appear. Maybe try a different playlist also?

**Comment by anmary** [comment]
I tried the run the script again but this time right at the beginning, I have this error 
``` 
2015-02-04 08:01:33 [697] [WARNING] base.py:143:get_response Not Found: /socket.io/1/
Gathering tracks for playlist Starred Tracks
(1/5306) Found 'Noah And The Whale - The First Days Of Spring' in Google Music
(2/5306) Found 'Iron & Wine - Such Great Heights' in Google Music
2015-02-04 08:01:51 [697] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /portify/transfer/start
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyportify/views.py", line 114, in transfer_start
    transfer_playlists(lists)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyportify/views.py", line 158, in transfer_playlists
    sp_track.load()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spotify/track.py", line 80, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spotify/utils.py", line 240, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
```

**Comment by rckclmbr** [comment]
@anmary it looks like wherever you're running this (is it a vm?) doesn't have internet access.  Check your network settings.

**Comment by ScheerMT** [comment]
Its weird though that two songs are found and then it errors out.. or am i misreading the log?

**Comment by rckclmbr** [comment]
Oh you're right @ScheerMT I didn't see that.  It doesn't look to me like there's anything in the code that would be causing this problem.

@anmary is there any reason you can think of that a connection to spotify (i believe it's api.spotify.com) would timeout?  How fast is your internet?  Do you have packet loss to api.spotify.com?

**Comment by anmary** [comment]
I ran the script again and it worked but I have a new error right at the end.
```
{\n   "response_code": "TOO_MANY_ITEMS"\n  },\n  {\n   "response_code": "TOO_MANY_ITEMS"\n  },\n  {\n   "response_code": "TOO_MANY_ITEMS"\n  },\n  {\n   "response_code": "TOO_MANY_ITEMS"\n  }\n ]\n}\n') 
```

My playlist contains 5306 songs, what's the limit ?

**Comment by rckclmbr** [comment]
Playlists on Google Music can only have a max of 1000 songs, so you'll need to split your playlist into multiple playlists and try the transfer again.

**Comment by anmary** [comment]
OK thanks.

**Comment by rckclmbr** [comment]
Another ticket is tracking the 1000 song limit.
