### ISSUE TITLE
-bash: pyportify: command not found

### ISSUE THREAD

**Issue by rodneystrong** [rckclmbr/pyportify#87]
OSX Sierra

Using instructions on the readme. 
After running pip3 install pyportify got this error at the end: 
````
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/LICENSE.txt'
````
After sudo pip3 install pyportify got this: 
````
The directory '/Users/aleeex/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/aleeex/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pyportify in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: certifi in /usr/local/lib/python3.6/site-packages (from pyportify)
Requirement already satisfied: requests==2.7.0 in /usr/local/lib/python3.6/site-packages (from pyportify)
Requirement already satisfied: aiohttp==1.1.5 in /usr/local/lib/python3.6/site-packages (from pyportify)
Requirement already satisfied: six==1.9.0 in /usr/local/lib/python3.6/site-packages (from pyportify)
Requirement already satisfied: chardet in /usr/local/lib/python3.6/site-packages (from aiohttp==1.1.5->pyportify)
Requirement already satisfied: yarl>=0.5.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==1.1.5->pyportify)
Requirement already satisfied: async-timeout>=1.1.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==1.1.5->pyportify)
Requirement already satisfied: multidict>=2.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==1.1.5->pyportify)
````

Then tried to run pyportify then got this: 
````
-bash: pyportify: command not found
````
I ran brew install libffi according to this issue: https://github.com/rckclmbr/pyportify/issues/5
But still no luck. I also ran sudo pyportify but nothing. 

Any ideas?

**Comment by barzev** [comment]
Same issue here.

**Comment by dayidp** [comment]
Try this:
Uninstall pyportify, then reinstall.

$ pip3 uninstall pyportify
$ sudo -H pip3 install pyportify

Let me know if that helped!
