### ISSUE TITLE
Character encoding maybe?

### ISSUE THREAD

**Issue by bennimmo** [rckclmbr/pyportify#9]
When trying to find songs with special characters e.g. José Gonzáles it stopped with the following dump...

2015-01-18 10:47:18 [1] [ERROR] base.py:231:handle_uncaught_exception Internal Server Error: /portify/transfer/start
Traceback (most recent call last):
  File "/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ve/local/lib/python2.7/site-packages/pyportify/views.py", line 113, in transfer_start
    transfer_playlists(lists)
  File "/ve/local/lib/python2.7/site-packages/pyportify/views.py", line 168, in transfer_playlists
    print "(%s/%s) Found '%s' in Google Music" % (i+1, track_count, search_query)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 18: ordinal not in range(128)

**Comment by rckclmbr** [comment]
That's exactly what it was, fixed by 625e27c80673e7364bfd5a58f9cf993d02ac9a6a.  Thanks for the report.
