### ISSUE TITLE
SSL Certificate Verify Failed From Docker

### ISSUE THREAD

**Issue by warmwaffles** [rckclmbr/pyportify#92]
```
docker run -t -i --rm -p 3132:3132 rckclmbr/pyportify
```

Will result in the following output

```
Listening on http://0.0.0.0:3132
Please open your browser window to http://localhost:3132
Error handling request
Traceback (most recent call last):
  File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ve/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ve/lib/python3.4/site-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/ve/lib/python3.4/site-packages/aiohttp/web.py", line 96, in handle_request
    resp = yield from handler(request)
  File "/ve/lib/python3.4/site-packages/pyportify/middlwares.py", line 18, in index_handler
    ret = yield from handler(request)
  File "/ve/lib/python3.4/site-packages/pyportify/app.py", line 51, in google_login
    token = yield from g.login(email, password)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/ve/lib/python3.4/site-packages/pyportify/google.py", line 28, in login
    res = gpsoauth.perform_master_login(username, password, android_id)
  File "/ve/lib/python3.4/site-packages/pyportify/gpsoauth/__init__.py", line 65, in perform_master_login
    return _perform_auth_request(data)
  File "/ve/lib/python3.4/site-packages/pyportify/gpsoauth/__init__.py", line 21, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/ve/lib/python3.4/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/ve/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/ve/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/ve/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/ve/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

This happens when I try to sign in to google.

**Comment by rckclmbr** [comment]
Docker image is hosed and hasn't been updated in a while, would appreciate it if someone could update the dockerfile and I'll push a new image

**Comment by warmwaffles** [comment]
@rckclmbr good to know. I'll try cloning and building the image from scratch. hub.docker.com says it is 5 days old?

**Comment by warmwaffles** [comment]
Even building from scratch still has this issue

```sh
docker-compose build --no-cache
docker-compose up
```

```
Creating network "pyportify_default" with the default driver
Creating pyportify_web_1
Attaching to pyportify_web_1
web_1  | Error handling request
web_1  | Traceback (most recent call last):
web_1  |   File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
web_1  |     body=body, headers=headers)
web_1  |   File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
web_1  |     self._validate_conn(conn)
web_1  |   File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
web_1  |     conn.connect()
web_1  |   File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
web_1  |     ssl_version=resolved_ssl_version)
web_1  |   File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
web_1  |     return context.wrap_socket(sock, server_hostname=server_hostname)
web_1  |   File "/usr/lib/python3.4/ssl.py", line 365, in wrap_socket
web_1  |     _context=self)
web_1  |   File "/usr/lib/python3.4/ssl.py", line 583, in __init__
web_1  |     self.do_handshake()
web_1  |   File "/usr/lib/python3.4/ssl.py", line 810, in do_handshake
web_1  |     self._sslobj.do_handshake()
web_1  | ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/ve/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
web_1  |     timeout=timeout
web_1  |   File "/ve/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
web_1  |     raise SSLError(e)
web_1  | requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/ve/lib/python3.4/site-packages/aiohttp/server.py", line 265, in start
web_1  |     yield from self.handle_request(message, payload)
web_1  |   File "/ve/lib/python3.4/site-packages/aiohttp/web.py", line 96, in handle_request
web_1  |     resp = yield from handler(request)
web_1  |   File "/ve/lib/python3.4/site-packages/pyportify/middlwares.py", line 18, in index_handler
web_1  |     ret = yield from handler(request)
web_1  |   File "/ve/lib/python3.4/site-packages/pyportify/app.py", line 51, in google_login
web_1  |     token = yield from g.login(email, password)
web_1  |   File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
web_1  |     res = func(*args, **kw)
web_1  |   File "/ve/lib/python3.4/site-packages/pyportify/google.py", line 28, in login
web_1  |     res = gpsoauth.perform_master_login(username, password, android_id)
web_1  |   File "/ve/lib/python3.4/site-packages/pyportify/gpsoauth/__init__.py", line 65, in perform_master_login
web_1  |     return _perform_auth_request(data)
web_1  |   File "/ve/lib/python3.4/site-packages/pyportify/gpsoauth/__init__.py", line 21, in _perform_auth_request
web_1  |     headers={'User-Agent': useragent})
web_1  |   File "/ve/lib/python3.4/site-packages/requests/api.py", line 109, in post
web_1  |     return request('post', url, data=data, json=json, **kwargs)
web_1  |   File "/ve/lib/python3.4/site-packages/requests/api.py", line 50, in request
web_1  |     response = session.request(method=method, url=url, **kwargs)
web_1  |   File "/ve/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
web_1  |     resp = self.send(prep, **send_kwargs)
web_1  |   File "/ve/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
web_1  |     r = adapter.send(request, **kwargs)
web_1  |   File "/ve/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
web_1  |     raise SSLError(e, request=request)
web_1  | requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by sergesyrota** [comment]
Same error from Ubuntu. And just can't figure out what's the issue, as certificate appears valid, and curl connects without a problem :(

**Comment by rckclmbr** [comment]
Need to install python3 with SSL.  See #71.   I may just remove docker support, unless someone wants to fix it.
