### ISSUE TITLE
Broken finding songs in Google Play music

### ISSUE THREAD

**Issue by baileywickham** [rckclmbr/pyportify#96]
Almost all songs cant be transferred from and found in Google Play.

**Comment by DanielsWrath** [comment]
Same problem over here, nothing can be found

**Comment by rckclmbr** [comment]
Google keeps changing their api. I'll take a look this weekend

**Comment by rckclmbr** [comment]
I haven't had any time to look at this, are people still seeing issues?  Also, do you have a subscription to Google Music?

**Comment by contherad** [comment]
I have both a google music subscription and a spotify subscription. i just tried to sync my playlist and i keep getting an exception. 

> Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/usr/lib64/python3.5/site-packages/aiohttp/web.py", line 96, in handle_request
    resp = yield from handler(request)
  File "/usr/lib/python3.5/site-packages/pyportify/middlwares.py", line 18, in index_handler
    ret = yield from handler(request)
  File "/usr/lib/python3.5/site-packages/pyportify/app.py", line 117, in transfer_start
    yield from transfer_playlists(request, s, g, lists)
  File "/usr/lib/python3.5/site-packages/pyportify/app.py", line 141, in transfer_playlists
    sp_playlist_uri)
  File "/usr/lib/python3.5/site-packages/pyportify/spotify.py", line 77, in fetch_playlist_tracks
    ret = yield from self.fetch_saved_tracks()
  File "/usr/lib/python3.5/site-packages/pyportify/spotify.py", line 71, in fetch_saved_tracks
    tracks = yield from self._http_get_all(url)
  File "/usr/lib/python3.5/site-packages/pyportify/spotify.py", line 61, in _http_get_all
    data = yield from self._http_get(url)
  File "/usr/lib/python3.5/site-packages/pyportify/spotify.py", line 122, in _http_get
    raise Exception("Error: {0}, url: {1}".format(data, url))
Exception: Error: {'error': {'status': 403, 'message': 'Insufficient client scope'}}, url: https://api.spotify.com/v1/me/tracks

**Comment by contherad** [comment]
I had an issue, but importing one playlist at a time seemed to resolve it.

**Comment by Conorbro** [comment]
All the playlists I try import from Spotify are just empty when viewed in Google Play Music.

**Comment by rckclmbr** [comment]
Are your playlists larger than 1000 songs? Are you still paying for a
spotify account?

**Comment by Conorbro** [comment]
The playlists are under 1000 songs in length and I'm still a Spotify premium member.
